name: thinkerx
description: ThinkerX is a effective tool collection.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ">=0.5.7+3 <2.0.0"
  provider: ^4.1.3
  intl: ^0.16.1
  auto_route: ^0.6.7
  path_provider: ^1.6.11
  fluttertoast: ^7.0.4
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.7+4
  dio: ^3.0.9
  progress_dialog: ^1.2.4
  flutter_colorpicker: ^0.3.4
  qr_flutter: ^3.1.0
  image_gallery_saver: ^1.5.0
  permission_handler: ^5.0.1
  qrscan: ^0.2.17
  crypto: ^2.1.4
  file_picker: ^1.13.0
  device_info: ^0.4.2+4
  webview_flutter: ^0.3.22+1
  flutter_jscore: ^0.1.1
  lpinyin: ^1.0.8
  image: ^2.1.12
  sqflite: ^1.3.1
  floor: ^0.14.0
  flutter_swiper: ^1.1.6
  marquee: ^1.5.2
  url_launcher: ^5.5.0
  image_cropper: ^1.3.0
  package_info: ^0.4.3
  share: '>=0.6.4+5 <2.0.0'
  flutter_spinkit: ^4.1.2
  quick_actions: ^0.4.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  floor_generator: ^0.14.0
  build_runner:

flutter_intl:
  enabled: true
  class_name: AppLocale
  main_locale: zh_CN
  localizely:
    project_id: 0262cc4b-cc72-4aa1-83a0-a267840bfc24

flutter:
  uses-material-design: true
  assets:
    - assets/icons/empty_box.svg
    - assets/icons/scan_qr_code.svg
    - assets/web/js/nzh.min.js
    - assets/web/js/relationship.min.js
    - assets/images/garbage_dry.png
    - assets/images/garbage_harmful.png
    - assets/images/garbage_recyclable.png
    - assets/images/garbage_wet.png
    - assets/images/app_logo.png
    - assets/images/about_background.jpg
    - assets/images/home_banner_1.jpg
    - assets/images/home_banner_2.jpg
